### ISSUE TITLE
can't use CHRP

### ISSUE THREAD

**Issue by snipsnap17** [nicsure/QuanshengDock#1] opened 2024-01-08 16:22 UTC
Thanks for this beautiful program!

Have two radios, on both supplied with your fimware, it is't possible to use Chirp anymore. after reflashing okay, but then thia magnificant program isn't usable anymore.

**Comment by nicsure** [comment] 2024-01-08 18:39
It shouldn't affect CHIRP as the firmware is essentially just egzumer, it doesn't mess with the eeprom flashing or anything. I'll look into why this is happening.

**Comment by victor7376** [comment] 2024-01-08 18:45
Just tried Chirp & it states 'bad header' so cant download or upload from the radio

**Comment by nicsure** [comment] 2024-01-08 19:14
Interesting, That's kind of surprising. I'll run CHIRP myself and try to see what the problem is.

**Comment by nicsure** [comment] 2024-01-08 19:19
Oh I know what's happening. The radio is sending display information constantly, that's what's confusing CHIRP. I can sort that out.

**Comment by nicsure** [comment] 2024-01-08 20:34
I've made a temporary solution for now. It requires reflashing the firmware with the release I've just updated on the firmware page. In the radio menu you'll find a new option called "Remote", if you set this to "OFF" CHIRP should then work. This setting defaults to "ON" every time the radio is powered up or reset.

**Comment by ErikS-web** [comment] 2024-01-10 19:01
Nice solution :+!: 

Suggest to correct title and add the "I", before closing, this issue as solved.

**Comment by ErikS-web** [comment] 2024-01-10 20:49
Where is this new firmware published ?

I only see release 1 firmware at [releases ( 4 days old) ](https://github.com/nicsure/quansheng-dock-fw/releases)

**Comment by nicsure** [comment] 2024-01-11 18:51
I didn't actually make a new release, just replaced the bin file.

**Comment by ErikS-web** [comment] 2024-01-17 18:27
Solution work fine:

Menu 60.`Remote` is default ON (after power-up). 

And can be set to "OFF" before using Chirp.

Just one question/suggestion: 
_Could it be made possible to change this parameter to OFF from PC  in QS-Dock ?_

Than..._This item can be closed ;-)_

**Closed** 2024-01-22 02:53 UTC
